#!/bin/sh /etc/rc.common

START=90
STOP=21

USE_PROCD=0

start() {
	/usr/lib/gfc-client/deploy/immortalwrt/gfc-routing.sh start
}

stop() {
	/usr/lib/gfc-client/deploy/immortalwrt/gfc-routing.sh stop
}

restart() {
	stop
	start
}
