#!/bin/sh /etc/rc.common

START=86
STOP=25
USE_PROCD=1

start_service() {
	[ -f /etc/gfc-client/gfc.env ] && . /etc/gfc-client/gfc.env
	local user="${GFC_MOSDNS_USER:-mosdns}"
	[ -f /etc/gfc-client/mosdns/easymosdns/config.yaml ] || return 0
	procd_open_instance
	procd_set_param command /usr/bin/mosdns start -c /etc/gfc-client/mosdns/easymosdns/config.yaml
	procd_set_param user "$user"
	procd_set_param respawn 5 10 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}
