#!/bin/sh /etc/rc.common

START=92
STOP=18
USE_PROCD=1

start_service() {
	mkdir -p /etc/gfc-client /var/lib/gfc-client /var/log/gfc-client
	procd_open_instance
	procd_set_param command /usr/bin/gfc-agent
	procd_set_param env GFC_ENV_FILE=/etc/gfc-client/gfc.env
	procd_set_param env GFC_PLATFORM=immortalwrt
	procd_set_param env GFC_ROOT=/usr/lib/gfc-client
	procd_set_param env GFC_ETC=/etc/gfc-client
	procd_set_param env GFC_LIB=/var/lib/gfc-client
	procd_set_param env GFC_LOG_DIR=/var/log/gfc-client
	procd_set_param respawn 5 10 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}
