#!/bin/sh /etc/rc.common

START=88
STOP=22
USE_PROCD=1

start_service() {
	[ -f /etc/gfc-client/sing-box.json ] || return 0
	procd_open_instance
	procd_set_param command /usr/bin/sing-box run -c /etc/gfc-client/sing-box.json
	procd_set_param respawn 5 10 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}
