# Control plane install parameter helpers (source only).
# shellcheck shell=bash

gfc_cp_default_ip() {
  hostname -I 2>/dev/null | awk '{print $1}'
}

gfc_cp_normalize_url() {
  local input=${1:-}
  local port=${2:-8181}
  local scheme=${3:-http}
  input=$(echo "$input" | tr -d '[:space:]')
  [[ -n "$input" ]] || return 1
  if [[ "$input" == *"://"* ]]; then
    echo "$input"
    return 0
  fi
  if [[ "$input" == \[*\]* ]]; then
    if [[ "$input" == *:* ]]; then
      echo "${scheme}://${input}"
    else
      echo "${scheme}://${input}:${port}"
    fi
    return 0
  fi
  if [[ "$input" == *:* ]]; then
    echo "${scheme}://${input}"
    return 0
  fi
  echo "${scheme}://${input}:${port}"
}

gfc_cp_prompt_default() {
  local var_name=$1
  local prompt=$2
  local default=$3
  local input
  read -r -p "$prompt [$default]: " input
  if [[ -z "$input" ]]; then
    printf -v "$var_name" '%s' "$default"
  else
    printf -v "$var_name" '%s' "$input"
  fi
}

gfc_cp_collect_install_config_interactive() {
  local default_ip
  default_ip=$(gfc_cp_default_ip)
  [[ -n "$default_ip" ]] || default_ip="127.0.0.1"

  echo ""
  echo "==> 控制平台安装参数（直接回车采用默认值）"
  echo "    对外 API 地址用于客户端线路码、节点/客户端连接控制面"
  echo "    支持 IP 或域名，例如 ${default_ip} / api.example.com"
  echo ""

  local host port host_fb scheme use_https
  gfc_cp_prompt_default host "控制平台对外地址（IP 或域名）" "$default_ip"
  gfc_cp_prompt_default port "API 端口" "8181"
  read -r -p "备用对外地址（IP 或域名，可留空）: " host_fb
  read -r -p "对外 API 使用 HTTPS？[y/N]: " use_https
  if [[ "$use_https" =~ ^[Yy]$ ]]; then
    scheme=https
  else
    scheme=http
  fi

  CONTROL_PLANE_HOST=$host
  API_PORT=$port
  GFC_PUBLIC_URL=$(gfc_cp_normalize_url "$host" "$port" "$scheme")
  if [[ -n "$host_fb" ]]; then
    CONTROL_PLANE_HOST_FALLBACK=$host_fb
    GFC_PUBLIC_URL_FALLBACK=$(gfc_cp_normalize_url "$host_fb" "$port" "$scheme")
  else
    CONTROL_PLANE_HOST_FALLBACK=
    GFC_PUBLIC_URL_FALLBACK=
  fi

  # If primary is bare IPv4, also set GFC_PUBLIC_IP for line-code IP fallback
  if [[ "$host" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    GFC_PUBLIC_IP=$host
  else
    GFC_PUBLIC_IP=
  fi
  GFC_PUBLIC_PORT=$port

  export CONTROL_PLANE_HOST CONTROL_PLANE_HOST_FALLBACK API_PORT
  export GFC_PUBLIC_URL GFC_PUBLIC_URL_FALLBACK GFC_PUBLIC_IP GFC_PUBLIC_PORT
}

gfc_cp_load_install_env_file() {
  local file=$1
  [[ -f "$file" ]] || return 1
  set -a
  # shellcheck disable=SC1090
  source "$file"
  set +a
  if [[ -z "${GFC_PUBLIC_URL:-}" && -n "${CONTROL_PLANE_HOST:-}" ]]; then
    GFC_PUBLIC_URL=$(gfc_cp_normalize_url "$CONTROL_PLANE_HOST" "${API_PORT:-8181}" "${GFC_PUBLIC_SCHEME:-http}")
    export GFC_PUBLIC_URL
  fi
  if [[ -z "${GFC_PUBLIC_URL_FALLBACK:-}" && -n "${CONTROL_PLANE_HOST_FALLBACK:-}" ]]; then
    GFC_PUBLIC_URL_FALLBACK=$(gfc_cp_normalize_url "$CONTROL_PLANE_HOST_FALLBACK" "${API_PORT:-8181}" "${GFC_PUBLIC_SCHEME:-http}")
    export GFC_PUBLIC_URL_FALLBACK
  fi
  export GFC_PUBLIC_PORT="${GFC_PUBLIC_PORT:-8181}"
  return 0
}

gfc_cp_validate_install_config() {
  local err=0
  if [[ -z "${GFC_PUBLIC_URL:-}" ]]; then
    echo "ERROR: 未设置 GFC_PUBLIC_URL / CONTROL_PLANE_HOST"
    err=1
  fi
  if command -v curl &>/dev/null; then
    echo "==> 检查本机 API（安装后再次验证）"
    if curl -fsS --connect-timeout 3 "http://127.0.0.1:${API_PORT:-8181}/healthz" >/dev/null 2>&1; then
      echo "    OK 本机 API 已在运行"
    else
      echo "    （首次安装：构建启动后将监听 ${API_PORT:-8181}）"
    fi
  fi
  return "$err"
}

gfc_cp_write_env_file() {
  local env_file=${1:-.env}
  local install_env=${2:-deploy/control/install.env}

  mkdir -p "$(dirname "$install_env")"

  cat >"$env_file" <<EOF
# Generated by GFC control plane installer — re-run install-docker.sh to update
GFC_PUBLIC_URL=${GFC_PUBLIC_URL}
GFC_PUBLIC_URL_FALLBACK=${GFC_PUBLIC_URL_FALLBACK:-}
GFC_PUBLIC_IP=${GFC_PUBLIC_IP:-}
GFC_PUBLIC_PORT=${GFC_PUBLIC_PORT:-8181}
EOF
  chmod 600 "$env_file"

  cat >"$install_env" <<EOF
# GFC control plane install parameters backup
CONTROL_PLANE_HOST=${CONTROL_PLANE_HOST:-}
CONTROL_PLANE_HOST_FALLBACK=${CONTROL_PLANE_HOST_FALLBACK:-}
API_PORT=${API_PORT:-8181}
GFC_PUBLIC_URL=${GFC_PUBLIC_URL}
GFC_PUBLIC_URL_FALLBACK=${GFC_PUBLIC_URL_FALLBACK:-}
GFC_PUBLIC_IP=${GFC_PUBLIC_IP:-}
GFC_PUBLIC_PORT=${GFC_PUBLIC_PORT:-8181}
EOF
  chmod 600 "$install_env"
  echo "==> 已写入 $env_file"
  echo "==> 已写入 $install_env"
}

gfc_cp_show_install_summary() {
  echo ""
  echo "==> 安装参数摘要"
  echo "    对外 API(主): ${GFC_PUBLIC_URL}"
  if [[ -n "${GFC_PUBLIC_URL_FALLBACK:-}" ]]; then
    echo "    对外 API(备): ${GFC_PUBLIC_URL_FALLBACK}"
  fi
  echo "    Web 管理台:   http://$(gfc_cp_default_ip):5173 （本机）"
  echo ""
}
