package policyrouting

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/278946647/sip-proxy/gfc-client/internal/config"
)

const (
	OverlayNFTFile  = "user-overlay.nft"
	OverlayBakFile  = "user-overlay.nft.bak"
	OverlaySHFile   = "user-overlay.sh"
	OverlayMetaFile = "overlay-meta.json"
	DataplaneOK     = "nft usr_* overlay 已应用；域名组经 unbound:53 分流解析写入 usr_dom_* 与 domain-map.json；proxy 复用 0x2023→2022→gfctun。"
)

func (s *Service) overlayPath() string {
	return filepath.Join(s.cfg.Paths.Etc, DirName, OverlayNFTFile)
}

func (s *Service) overlayBakPath() string {
	return filepath.Join(s.cfg.Paths.Etc, DirName, OverlayBakFile)
}

func (s *Service) overlaySHPath() string {
	return filepath.Join(s.cfg.Paths.Etc, DirName, OverlaySHFile)
}

func (s *Service) overlayMetaPath() string {
	return filepath.Join(s.cfg.Paths.Etc, DirName, OverlayMetaFile)
}

// ApplyDataplane syncs usr_* sets and user overlay chains. Restores previous overlay on failure.
func (s *Service) ApplyDataplane(groups []Group, policies []Policy, env Env) error {
	if err := os.MkdirAll(filepath.Join(s.cfg.Paths.Etc, DirName), 0o755); err != nil {
		return err
	}
	if !nftTableExists() {
		return fmt.Errorf("inet gfc 表不存在：请先启动 gfc-routing")
	}
	if !nftChainExists("prerouting_user_overlay") || !nftChainExists("output_user_overlay") {
		return fmt.Errorf("缺少 prerouting_user_overlay / output_user_overlay：请更新并重载 gfc-routing 后再 apply")
	}

	lan := resolveLanIface(s.cfg)
	wan := s.cfg.ResolvedWanIface()
	mark := env.Mark
	if mark == "" {
		mark = "0x2023"
	}
	mark = normalizeMark(mark)

	gm := groupMap(groups)
	needed := collectNeededGroups(policies, gm)

	// Resolve ALL domain groups via unbound (mapping for UI); sync sets only for referenced.
	domMap, allResolved, err := buildDomainMap(groups)
	if err != nil {
		return err
	}
	_ = s.saveDomainMap(domMap)
	resolved := map[string][]string{}
	domainWarn := 0
	for _, g := range needed {
		if g.Kind == KindDomain {
			resolved[g.ID] = allResolved[g.ID]
			if entry, ok := domMap.Groups[g.ID]; ok {
				for _, de := range entry.Domains {
					if de.Error != "" || len(de.IPs) == 0 {
						domainWarn++
					}
				}
			}
		}
	}

	for _, g := range needed {
		elems := g.Members
		if g.Kind == KindDomain {
			elems = resolved[g.ID]
		}
		if err := syncUserSet(g, elems); err != nil {
			return err
		}
	}

	script, err := buildOverlayChainNFT(groups, policies, env, lan, wan, mark)
	if err != nil {
		return err
	}

	path := s.overlayPath()
	bak := s.overlayBakPath()
	prev, _ := os.ReadFile(path)
	if len(prev) > 0 {
		_ = os.WriteFile(bak, prev, 0o600)
	}
	if err := os.WriteFile(path, []byte(script), 0o600); err != nil {
		return err
	}

	sh := buildReloadShell(needed, resolved, path)
	if err := os.WriteFile(s.overlaySHPath(), []byte(sh), 0o755); err != nil {
		return err
	}

	if out, err := exec.Command("nft", "-f", path).CombinedOutput(); err != nil {
		if len(prev) > 0 {
			_ = os.WriteFile(path, prev, 0o600)
			_, _ = exec.Command("nft", "-f", path).CombinedOutput()
		} else {
			_ = flushUserOverlayChains()
			_ = os.Remove(path)
		}
		return fmt.Errorf("nft apply 失败: %v (%s)", err, strings.TrimSpace(string(out)))
	}
	note := DataplaneOK
	if domainWarn > 0 {
		note = fmt.Sprintf("%s；警告：%d 个域名经 unbound 未解析到 A 记录（usr_dom 可能不完整）", DataplaneOK, domainWarn)
	}
	writeOverlayMeta(s.overlayMetaPath(), true, note)
	return nil
}

func collectNeededGroups(policies []Policy, gm map[string]Group) []Group {
	seen := map[string]Group{}
	for _, p := range policies {
		if !p.Enabled {
			continue
		}
		for _, id := range []string{p.MatchSrcGroupID, p.MatchDstGroupID, p.MatchDomainGroupID} {
			if g, ok := gm[id]; ok {
				seen[g.ID] = g
			}
		}
	}
	out := make([]Group, 0, len(seen))
	for _, g := range seen {
		out = append(out, g)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].ID < out[j].ID })
	return out
}

func buildReloadShell(groups []Group, resolved map[string][]string, nftPath string) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Regenerated by policy-routing apply — re-create usr_* after inet gfc table recreate\n")
	b.WriteString("set -e\n")
	for _, g := range groups {
		name := setNameFor(g)
		elems := g.Members
		if g.Kind == KindDomain {
			elems = resolved[g.ID]
		}
		var create string
		if g.Kind == KindDomain {
			create = fmt.Sprintf("add set inet gfc %s { type ipv4_addr; flags timeout; timeout 1h; }", name)
		} else {
			create = fmt.Sprintf("add set inet gfc %s { type ipv4_addr; flags interval; }", name)
		}
		b.WriteString(fmt.Sprintf("nft list set inet gfc %s >/dev/null 2>&1 || nft -f - <<'SET'\n%s\nSET\n", name, create))
		b.WriteString(fmt.Sprintf("nft flush set inet gfc %s\n", name))
		if len(elems) > 0 {
			b.WriteString(fmt.Sprintf("nft -f - <<'ELEM'\nadd element inet gfc %s { %s }\nELEM\n", name, strings.Join(elems, ", ")))
		}
	}
	b.WriteString(fmt.Sprintf("nft -f %q\n", nftPath))
	return b.String()
}

func syncUserSet(g Group, elems []string) error {
	name := setNameFor(g)
	if name == "" {
		return fmt.Errorf("无效组类型 %s", g.Kind)
	}
	if !nftSetExists(name) {
		var create string
		if g.Kind == KindDomain {
			create = fmt.Sprintf("add set inet gfc %s { type ipv4_addr; flags timeout; timeout 1h; }", name)
		} else {
			create = fmt.Sprintf("add set inet gfc %s { type ipv4_addr; flags interval; }", name)
		}
		cmd := exec.Command("nft", "-f", "-")
		cmd.Stdin = strings.NewReader(create + "\n")
		if out, err := cmd.CombinedOutput(); err != nil {
			return fmt.Errorf("create set %s: %v (%s)", name, err, strings.TrimSpace(string(out)))
		}
	}
	if out, err := exec.Command("nft", "flush", "set", "inet", "gfc", name).CombinedOutput(); err != nil {
		return fmt.Errorf("flush set %s: %v (%s)", name, err, strings.TrimSpace(string(out)))
	}
	if len(elems) == 0 {
		return nil
	}
	line := fmt.Sprintf("add element inet gfc %s { %s }\n", name, strings.Join(elems, ", "))
	cmd := exec.Command("nft", "-f", "-")
	cmd.Stdin = strings.NewReader(line)
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("add element %s: %v (%s)", name, err, strings.TrimSpace(string(out)))
	}
	return nil
}

func flushUserOverlayChains() error {
	_ = exec.Command("nft", "flush", "chain", "inet", "gfc", "prerouting_user_overlay").Run()
	_ = exec.Command("nft", "flush", "chain", "inet", "gfc", "output_user_overlay").Run()
	return nil
}

func nftTableExists() bool {
	return exec.Command("nft", "list", "table", "inet", "gfc").Run() == nil
}

func nftChainExists(name string) bool {
	return exec.Command("nft", "list", "chain", "inet", "gfc", name).Run() == nil
}

func nftSetExists(name string) bool {
	return exec.Command("nft", "list", "set", "inet", "gfc", name).Run() == nil
}

func normalizeMark(mark string) string {
	mark = strings.TrimSpace(strings.ToLower(mark))
	if !strings.HasPrefix(mark, "0x") {
		return mark
	}
	hex := strings.TrimPrefix(mark, "0x")
	for len(hex) < 8 {
		hex = "0" + hex
	}
	return "0x" + hex
}

func sanitizeSetID(id string) string {
	var b strings.Builder
	for _, r := range id {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '_':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	out := b.String()
	if out == "" {
		return "x"
	}
	return out
}

func setNameFor(g Group) string {
	id := sanitizeSetID(g.ID)
	switch g.Kind {
	case KindSrcCIDR:
		return SetPrefixSrc + id
	case KindDstCIDR:
		return SetPrefixDst + id
	case KindDomain:
		return SetPrefixDom + id
	default:
		return ""
	}
}

func buildOverlayChainNFT(groups []Group, policies []Policy, env Env, lan, wan, mark string) (string, error) {
	var b strings.Builder
	b.WriteString("# GFC user policy overlay chains — generated by policy-routing apply\n")
	b.WriteString("# docs/USER_POLICY_ROUTING.md — pairing user-overlay.sh recreates usr_* after table reload\n")
	b.WriteString(fmt.Sprintf("# generated_at=%s proxy_mode=%s lan=%s wan=%s\n",
		time.Now().UTC().Format(time.RFC3339), env.ProxyMode, lan, wan))

	gm := groupMap(groups)

	b.WriteString("flush chain inet gfc prerouting_user_overlay\n")
	b.WriteString("flush chain inet gfc output_user_overlay\n")

	b.WriteString("add rule inet gfc prerouting_user_overlay ip daddr { 10.0.0.0/8, 127.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 } return\n")
	b.WriteString("add rule inet gfc prerouting_user_overlay ip daddr @bypass_ip return\n")
	b.WriteString("add rule inet gfc output_user_overlay ip daddr { 10.0.0.0/8, 127.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16 } return\n")
	b.WriteString("add rule inet gfc output_user_overlay ip daddr @bypass_ip return\n")

	sortPoliciesByRank(policies)
	bypassMode := strings.EqualFold(strings.TrimSpace(env.ProxyMode), "bypass")

	for _, p := range policies {
		if !p.Enabled {
			continue
		}
		match, err := matchExpr(p, gm)
		if err != nil {
			return "", err
		}
		comment := fmt.Sprintf("Override#%s %s", p.ID, sanitizeComment(p.Name))
		action := actionExpr(p.Action, mark)

		if lan != "" {
			b.WriteString(fmt.Sprintf("add rule inet gfc prerouting_user_overlay iifname %q %s %s comment %q\n", lan, match, action, comment))
		}
		if bypassMode && wan != "" {
			b.WriteString(fmt.Sprintf(
				"add rule inet gfc prerouting_user_overlay iifname %q ip saddr @customer_hosts %s %s comment %q\n",
				wan, match, action, comment+" wan",
			))
		}
		b.WriteString(fmt.Sprintf("add rule inet gfc output_user_overlay %s %s comment %q\n", match, action, comment+" out"))
	}
	return b.String(), nil
}

func matchExpr(p Policy, gm map[string]Group) (string, error) {
	var parts []string
	if p.MatchSrcGroupID != "" {
		g, ok := gm[p.MatchSrcGroupID]
		if !ok {
			return "", fmt.Errorf("源组缺失 %s", p.MatchSrcGroupID)
		}
		parts = append(parts, "ip saddr @"+setNameFor(g))
	}
	if p.MatchDstGroupID != "" {
		g, ok := gm[p.MatchDstGroupID]
		if !ok {
			return "", fmt.Errorf("目的组缺失 %s", p.MatchDstGroupID)
		}
		parts = append(parts, "ip daddr @"+setNameFor(g))
	}
	if p.MatchDomainGroupID != "" {
		g, ok := gm[p.MatchDomainGroupID]
		if !ok {
			return "", fmt.Errorf("域名组缺失 %s", p.MatchDomainGroupID)
		}
		parts = append(parts, "ip daddr @"+setNameFor(g))
	}
	if len(parts) == 0 {
		return "", fmt.Errorf("策略 %s 无匹配条件", p.Name)
	}
	return strings.Join(parts, " "), nil
}

func actionExpr(action, mark string) string {
	if action == ActionProxy {
		return fmt.Sprintf("ct mark set %s meta mark set ct mark accept", mark)
	}
	return "accept"
}

func sanitizeComment(s string) string {
	s = strings.ReplaceAll(s, `"`, "'")
	s = strings.ReplaceAll(s, "\n", " ")
	if len(s) > 64 {
		s = s[:64]
	}
	return s
}

func resolveLanIface(cfg *config.Config) string {
	if cfg == nil {
		return "br-lan"
	}
	if v := strings.TrimSpace(cfg.LanIface); v != "" {
		return v
	}
	path := filepath.Join(cfg.Paths.Etc, "network-roles.json")
	data, err := os.ReadFile(path)
	if err != nil {
		return "br-lan"
	}
	var roles map[string]any
	if json.Unmarshal(data, &roles) != nil {
		return "br-lan"
	}
	if lan, ok := roles["lan"].(string); ok && strings.TrimSpace(lan) != "" {
		return strings.TrimSpace(lan)
	}
	return "br-lan"
}

func writeOverlayMeta(path string, applied bool, note string) {
	raw, _ := json.MarshalIndent(map[string]any{
		"dataplane_applied": applied,
		"note":              note,
		"updated_at":        time.Now().UTC().Format(time.RFC3339),
	}, "", "  ")
	_ = os.WriteFile(path, raw, 0o600)
}

func readOverlayMeta(path string) (applied bool, note string) {
	data, err := os.ReadFile(path)
	if err != nil {
		return false, DataplanePending
	}
	var m map[string]any
	if json.Unmarshal(data, &m) != nil {
		return false, DataplanePending
	}
	applied, _ = m["dataplane_applied"].(bool)
	note, _ = m["note"].(string)
	if note == "" {
		if applied {
			note = DataplaneOK
		} else {
			note = DataplanePending
		}
	}
	return applied, note
}
